name: Kubescape scan Junit Format
on: [push, pull_request]
jobs: 
  kubescape2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: kubescape/github-action@main
        continue-on-error: true
        with:
          format: junit
      - name: Publish JUnit Test Report
        uses: mikepenz/action-junit-report@v3
        with:
          report_paths: "*.xml"